controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_link_link_01
      - link_01_link_02
      - link_02_link_03
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity